version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: madebydua_mongo
    environment:
      MONGO_INITDB_DATABASE: madebydua_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - madebydua
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "123456", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  backend:
    build:
      context: ./server
    container_name: madebydua_backend
    ports:
      - "5007:5007"
    environment:
      MONGODB_URI: mongodb://admin:123456@mongo:27017/madebydua_db?authSource=admin&serverSelectionTimeoutMS=30000&connectTimeoutMS=30000
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
      PORT: 5007
    restart: unless-stopped
      
    networks:
      - madebydua
    volumes:
      - uploads_data:/app/uploads   
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build:
      context: ./client
    container_name: madebydua_frontend
    ports:
      - "5174:80"
    networks:
      - madebydua
    depends_on:
      backend:
        condition: service_started   

networks:
  madebydua:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  uploads_data:
    driver: local