version: "3.8"

services:
  backend: 
   build: ./server
   container_name: madebydua_backend
   ports:
     - 5007:5007

   env_file:
     - ./server/.env

  frontend: 
   build: ./client
   container_name: madebydua_frontend
   ports:
     - 5180:80

   env_file:
     - ./server/.env  

  